Fix 1px overflow
ansible/ansible-ui pull request #1143
Opened 2023-10-30 17:28 UTC by keithjgrant

* fixes 1px scroll issue on some mobile screen sizes
* updates hub/eda masthead to match awx

2023-10-30 18:45 UTC, jamestalton commented
I am now seeing 1px at the bottom of all the screens.
i.e. that white line under the shadow.

![Screenshot 2023-10-30 at 2 44 58 PM](https://github.com/ansible/ansible-ui/assets/6277895/0c953397-97cb-4a84-b3e1-b4321ad3dedd)

2023-10-30 19:21 UTC, jamestalton requested changes

2023-10-30 19:21 UTC, jamestalton commented on framework/PageLayout.tsx
> +          height: 'calc(100% - 1px)',
I am now seeing 1px at the bottom of all the screens.

2023-11-01 21:02 UTC, lgalis approved these changes
LGTM

2023-11-02 16:13 UTC, merged