Add copy URL to remote and remote registries
ansible/ansible-ui pull request #1255
Opened 2023-11-21 18:53 UTC by nixocio

Add copy URL to remote and remote registries

2023-11-27 14:19 UTC, AlexSCorey requested changes

2023-11-27 14:19 UTC, AlexSCorey commented on frontend/hub/collections/CollectionDetails.tsx
> +                `Note Installing collection with ansible-galaxy is only supported in ansible 2.9+`
```suggestion
                `Note: Installing collection with ansible-galaxy is only supported in ansible 2.9+`
```

2023-11-27 16:23 UTC, nixocio commented on framework/PageCells/CopyCell.tsx
> +      textAriaLabel={t('Copyable input')}
This phrase comes from PR default text.

2023-11-29 21:41 UTC, skochay330 approved these changes

2023-11-29 21:59 UTC, ShaiahWren commented
Could you add a before/after photo? This will give context to us reviewers.

2023-11-30 15:37 UTC, merged