Workflow visualizer remove all nodes and screen state management
ansible/ansible-ui pull request #1294
Opened 2023-12-01 15:00 UTC by marshmalien

2023-12-01 17:07 UTC, AlexSCorey requested changes
I do think we should add the remove element in this PR.  The other comments should be added in this PR, or become issues (if you agree with them) so we can track them.

2023-12-01 17:07 UTC, AlexSCorey commented on frontend/awx/resources/templates/WorkflowVisualizer/hooks/useRemoveAllNodes.tsx
> +      header: t('Identifier'),
The identifier becomes that same value as "alias" - which is a field in the node form - if the user adds a value there. In the case where they do not, the identifier comes from the API and may not be of much use for the user.  

To help us with this we do have a util function called `stringIsUUID`

Perhaps in this delete modal we should have a alias/idenifier column, a resource name column..... what do you think?

2023-12-05 15:21 UTC, marshmalien commented on frontend/awx/resources/templates/WorkflowVisualizer/components/DeletedNode.tsx
> +export const DeletedNode: FC<CustomNodeProps & WithDragNodeProps & WithSelectionProps> = ({
Let's do it in a future iteration

2023-12-05 15:25 UTC, AlexSCorey commented on frontend/awx/resources/templates/WorkflowVisualizer/hooks/useRemoveAllNodes.tsx
> +      header: t('Identifier'),
@marshmalien and I spoke offline and my concerns have been addressed.  I agree with this approach.

2023-12-05 18:21 UTC, AlexSCorey approved these changes
This looks great!

2023-12-05 18:40 UTC, merged