Hub: fixing flaky remotes and remote registries tests
ansible/ansible-ui pull request #1477
Opened 2024-01-17 21:45 UTC by akus062381

2024-01-18 13:13 UTC, ZitaNemeckova approved these changes

2024-01-18 15:45 UTC, nixocio requested changes

2024-01-18 15:49 UTC, akus062381 commented on cypress/e2e/hub/remote-registries.cy.ts
> +    cy.url().should('include', `${remoteRegistryName}`);
this URL didn't work on my system, which is why I changed it

2024-01-21 12:26 UTC, vishsanghishetty commented on cypress/e2e/hub/remote-registries.cy.ts
> +    cy.url().should('include', `${remoteRegistryName}`);
`remote-registries/details/${remoteRegistryName}`

2024-02-08 15:56 UTC, closed without merging