[AAP-8294] Add details tab to inventory group page
ansible/ansible-ui pull request #1531
Opened 2024-01-28 02:19 UTC by matoval

Jira ticket: https://issues.redhat.com/browse/AAP-8294

Add details tab to inventory group page

Before:
![image](https://github.com/ansible/ansible-ui/assets/53712446/4bd18f82-9872-41df-afa5-1cc9f0282b3f)

After:
![image](https://github.com/ansible/ansible-ui/assets/53712446/519abbf7-bdc3-4528-8cac-dd22a50b03cb)

2024-02-01 19:23 UTC, kialam commented
Nice work, I'm seeing a few UI discrepancies and errors below:

![Screenshot 2024-02-01 at 11 20 23 AM](https://github.com/ansible/ansible-ui/assets/2293210/cff5bf96-e01d-4599-b565-5eb61382d080)
Inventory Groups header name shouldn't be present in a tab view
![edit-group](https://github.com/ansible/ansible-ui/assets/2293210/c12d9628-05bc-46fa-a7d2-5d7660abf2dd)
The edit group button does not go to the inventory edit form.

2024-02-01 19:23 UTC, kialam requested changes

2024-02-01 21:04 UTC, matoval commented on cypress/e2e/awx/resources/inventoryGroup.cy.ts
> +      `/infrastructure/inventories/inventory/${inventory.id}/groups?page=1&perPage=10&sort=name`
I don't think we can use AwxRoute outside of a React component since we can't use a hook like useGetPage to build the url.

2024-02-02 00:07 UTC, kialam approved these changes
LGTM. I pulled this down and tested locally. Great job!

2024-02-02 00:08 UTC, merged