Fixes  redirection issue for deletion of custom credential type from the details page
ansible/ansible-ui pull request #1619
Opened 2024-02-08 16:41 UTC by vishsanghishetty

## Description
This PR is for [ticket](https://issues.redhat.com/browse/AAP-20602) 

**Expected:**

- [x] Delete a custom credential from its details page.
- [x] Once deleted, the page redirects to the list page of custom credential types and refreshes the list to display the modified.

**Actual:** 

- [x] Delete a custom credential from its details page.
- [x] Once deleted, the page displays React not found error.

2024-02-09 02:18 UTC, kialam commented on frontend/awx/access/credential-types/CredentialTypePage/CredentialTypePage.tsx
> +  const actions = useCredentialTypeRowActions({
```suggestion
  const actions = useCredentialTypeRowActions({
```

2024-02-09 02:31 UTC, kialam requested changes
This is most of the way there 🥇. We can leverage props here and pass an on delete credential type handler in both toolbar and row action hooks and pass it to the `useDeleteCredentialTypes` hook. Let me know if there are any questions - I am happy to pair on this with you as well.

2024-02-09 02:31 UTC, kialam commented on frontend/awx/access/credential-types/CredentialTypePage/CredentialTypePage.tsx
> +    isDetailsPageAction: true,
Looks like this prop isn't being used anywhere in the hook. We can remove it and just pass a single prop here.

2024-02-09 02:31 UTC, kialam commented on frontend/awx/access/credential-types/CredentialTypePage/CredentialTypePage.tsx
>    });
```suggestion
  const actions = useCredentialTypeRowActions(() => pageNavigate(AwxRoute.CredentialTypes));
```

2024-02-09 02:31 UTC, kialam commented on frontend/awx/access/credential-types/CredentialTypePage/CredentialTypePage.tsx
> +  const pageActions = actions;
Remove this

2024-02-09 02:31 UTC, kialam commented on frontend/awx/access/credential-types/CredentialTypePage/CredentialTypePage.tsx
> +            actions={pageActions}
```suggestion
            actions={actions}
```

2024-02-09 02:31 UTC, kialam commented on frontend/awx/access/credential-types/hooks/useCredentialTypeActions.tsx
> +}) {
```suggestion
export function useCredentialTypeRowActions(onCredentialTypesDeleted: (credentialType: CredentialType[]) => void) {
```

2024-02-09 02:31 UTC, kialam commented on frontend/awx/access/credential-types/hooks/useCredentialTypeActions.tsx
> +  const { onCredentialTypesDeleted } = options;
remove

2024-02-09 02:31 UTC, kialam commented on frontend/awx/access/credential-types/hooks/useCredentialTypeActions.tsx
> -  const rowActions = useMemo<IPageAction<CredentialType>[]>(() => {
We'll want to keep this `rowActions` to return later

2024-02-09 02:31 UTC, kialam commented on frontend/awx/access/credential-types/hooks/useCredentialTypeActions.tsx
>  export function useCredentialTypeToolbarActions(view: IAwxView<CredentialType>) {
We can leverage passing the same on delete credential prop here as well.
```suggestion
export function useCredentialTypeToolbarActions(onCredentialTypesDeleted: (credentialType: CredentialType[]) => void) {
```

2024-02-09 02:31 UTC, kialam commented on frontend/awx/access/credential-types/hooks/useCredentialTypeActions.tsx
> +  const deleteCredentialTypes = useDeleteCredentialTypes(view.unselectItemsAndRefresh);
```suggestion
  const deleteCredentialTypes = useDeleteCredentialTypes(onCredentialTypesDeleted);
```

2024-02-14 22:21 UTC, vishsanghishetty commented
> This is most of the way there 🥇. We can leverage props here and pass an on delete credential type handler in both toolbar and row action hooks and pass it to the `useDeleteCredentialTypes` hook. Let me know if there are any questions - I am happy to pair on this with you as well.

@kialam thanks for the feedback, much appreciated.

2024-02-16 01:19 UTC, kialam approved these changes
👍

2024-02-16 10:03 UTC, merged