AAP-8257 EE Add Edit Form
ansible/ansible-ui pull request #1630
Opened 2024-02-08 23:26 UTC by prat98

This PR is for [AAP-8257](https://issues.redhat.com/browse/AAP-8257) which encompasses the work around creating the add and edit forms on the new AWX UI.

2024-02-09 18:44 UTC, kialam commented on frontend/awx/administration/execution-environments/ExecutionEnvironmentForm.tsx
> +export interface IExecutionEnvInput {
Can we combine these two types into one?

2024-02-09 18:48 UTC, kialam approved these changes
pulled this down and tested locally. LGTM. I had one suggestion of combining the two interfaces for the form edit, however that's not a blocker for merging this work.

2024-02-09 18:55 UTC, kialam commented
@prat98 we'll probably want to wait until https://github.com/ansible/ansible-ui/pull/1638 is merged before merging this one (it will need to be refactored to use the new orgs select in the edit EE form)

2024-02-12 16:47 UTC, marshmalien requested changes
It looks like we need to filter the registry credential input field by kind `/credentials/?credential_type__kind=registry`. In the old UI screenshot below, there are no credential results, but there are 3 credentials in the new UI screenshot.

_Side-by-side shot of new vs old UI_
![Screenshot 2024-02-12 at 11 41 31 AM](https://github.com/ansible/ansible-ui/assets/15881645/47bc04a8-55da-44c5-8c55-355ca9e5845c)

![Screenshot 2024-02-12 at 11 43 49 AM](https://github.com/ansible/ansible-ui/assets/15881645/24773792-1e67-45be-83a9-ad0316fdee5c)

2024-02-12 20:06 UTC, marshmalien approved these changes
lgtm!! 🎉

2024-02-14 17:27 UTC, merged