Make JobsList reusable and add Host > Jobs List
ansible/ansible-ui pull request #1745
Opened 2024-02-27 19:21 UTC by daphnemaeve

Jira issue: https://issues.redhat.com/browse/AAP-8161

Uses work from InventoryHostJobs to create reusable JobsList component . Uses this component for Inventory > Host Jobs and Host > Jobs pages.

2024-02-29 21:53 UTC, kialam requested changes
Jobs list should be sorted by most recent run time otherwise this looks great.

2024-02-29 21:53 UTC, kialam commented on frontend/awx/resources/hosts/HostPage/HostJobs.tsx
> +  usePersistentFilters('inventories');
```suggestion
  usePersistentFilters('hosts');
```

2024-03-01 17:35 UTC, kialam approved these changes
This good to merge after we sort by most recently finished. 👍

2024-03-04 15:00 UTC, resoluteCoder approved these changes

2024-03-04 20:13 UTC, merged