[AAP-21457] Add workflow nodes output toolbar status bar
ansible/ansible-ui pull request #1834
Opened 2024-03-14 11:34 UTC by jerabekjiri

Issue: [AAP-21457](https://issues.redhat.com/browse/AAP-21457)

- Generalize `HostStatusBar` into a reusable `StatusBar` component.
- Create `HostStatusBar` and `WorkflowNodesStatusBar` components based on the `StatusBar` component.

![Screenshot from 2024-03-13 23-49-12](https://github.com/ansible/ansible-ui/assets/19647757/90d14854-3864-439f-878d-00f4c8fefc74)

![Screenshot from 2024-03-13 22-15-57](https://github.com/ansible/ansible-ui/assets/19647757/2774ffbc-63e5-42b4-a154-d92d17e2681d)

![Screenshot from 2024-03-14 22-22-37](https://github.com/ansible/ansible-ui/assets/19647757/20a3d25b-f505-4331-9a97-7ff6b8c62b65)

2024-03-14 13:32 UTC, nixocio requested changes

2024-03-14 13:32 UTC, nixocio commented on frontend/awx/views/jobs/JobOutput/StatusBar.tsx
> +      color: 'var(--pf-v5-global--danger-color--300)',
What about create a pfUnreachable color?

2024-03-14 13:32 UTC, nixocio commented on frontend/awx/views/jobs/JobOutput/StatusBar.tsx
> +    const jobStatus = status[key as keyof K] as StatusProps;
I am getting an error locally here.

<img width="416" alt="image" src="https://github.com/ansible/ansible-ui/assets/9053044/6e6e6505-210c-4e6d-b128-274bded118b8">

It seems like we could add default values to the color and label.

2024-03-14 17:41 UTC, jerabekjiri commented on frontend/awx/views/jobs/JobOutput/StatusBar.tsx
> +      color: 'var(--pf-v5-global--danger-color--300)',
done :)

2024-03-15 13:39 UTC, resoluteCoder approved these changes
lgtm

2024-03-15 15:54 UTC, nixocio approved these changes

2024-03-18 14:04 UTC, merged