Feature rbac wizard
ansible/ansible-ui pull request #1938
Opened 2024-04-03 21:36 UTC by keithjgrant

This provides the key building blocks necessary to finish building out RBAC wizards throughout the various products. EDA project -> add users and project -> add teams each provide a template that can be reused for most similar wizards.

2024-04-04 15:36 UTC, vidyanambiar commented
Could we merge these PRs into the feature rbac wizard branch as well?
https://github.com/ansible/ansible-ui/pull/1931
https://github.com/ansible/ansible-ui/pull/1941

2024-04-05 13:47 UTC, vidyanambiar approved these changes

2024-04-05 16:39 UTC, jamestalton requested changes

2024-04-05 16:39 UTC, jamestalton commented on frontend/eda/access/teams/components/steps/EdaSelectTeamsStep.tsx
> +const StyledTitle = styled(Title)`
I think we should avoid styling this.
If you put the elements in a <TextContent> PF then applies the right styles to the elements.

2024-04-05 17:02 UTC, jamestalton approved these changes

2024-04-05 21:06 UTC, merged