Schedules > Details tab
ansible/ansible-ui pull request #2092
Opened 2024-04-17 22:36 UTC by acruzgon

This PR closes [AAP-22731](https://issues.redhat.com/browse/AAP-22731)

1. Exceptions preview added in create schedule wizard
2. Schedule summary added in schedule details page
3. Rules preview added in schedule details page
4. Exceptions preview added in schedule details page

2024-04-18 13:56 UTC, AlexSCorey reviewed
This is looking really good.  A few kinks to work out.  Let me know if I can help!

2024-04-18 13:56 UTC, AlexSCorey commented on frontend/awx/views/schedules/components/RulesPreview.tsx
> +            ></RulesPreviewBody>
```suggestion
            <RulesPreviewBody
              ruleObject={element.rule.options}
              key={index}
              index={index}
            />
```

2024-04-18 13:56 UTC, AlexSCorey commented on frontend/awx/views/schedules/components/RulesPreview.tsx
> +        <RulesPreviewBody ruleString={props.rrule}></RulesPreviewBody>
```suggestion
        <RulesPreviewBody ruleString={props.rrule}/>
```

2024-04-18 13:56 UTC, AlexSCorey commented on frontend/awx/interfaces/Schedule.ts
> +  extra_data: object;
These items will not live at the top level of a schedule.  The only relation they have to a schedule is through the assigned resource.  Therefore we shouldn't need these interface properties.
```suggestion
```

2024-04-18 13:56 UTC, AlexSCorey commented on frontend/awx/views/schedules/SchedulePage/ScheduleDetails.tsx
> +                aria-label={t('Toggle to Local')}
```suggestion
                aria-label={t('Toggle to local')}
```

2024-04-18 22:36 UTC, matoval approved these changes
LGTM, ready to merge.

2024-04-19 14:40 UTC, AlexSCorey requested changes
This looks really good.  There are a few things that made it into this PR that don't belong to schedules.  I've made suggestions below.  Let me know if I can help!

2024-04-19 14:40 UTC, AlexSCorey commented on cypress/e2e/awx/views/schedules.cy.ts
> +  it.skip('can edit a schedule remove exceptions', () => {
can we activate this?

2024-04-19 14:40 UTC, AlexSCorey commented on frontend/awx/views/schedules/SchedulePage/ScheduleDetails.tsx
> +                history(
can we use the hook `usePageNavigate` here instead of react router dom hooks?

2024-04-19 14:40 UTC, AlexSCorey commented on frontend/awx/views/schedules/wizard/ScheduleReviewStep.tsx
> +  const timeoutDetail = getValueBasedOnJobType(node_type, '', timeoutString);
This won't apply to us.  Timeout is a value that lives on workflow approvals and they don't have schedules.

2024-04-19 14:40 UTC, AlexSCorey commented on frontend/awx/views/schedules/wizard/ScheduleReviewStep.tsx
> +
```suggestion
  const { wizardData, visibleSteps } = usePageWizard() as {
    wizardData: ScheduleFormWizard;
    visibleSteps: PageWizardStep[];
  };
  const {
    resource_type,
    resource,
    node_days_to_keep,
    name,
    description,
    startDateTime,
    timezone,
    exceptions,
  } = wizardData;
```

2024-04-19 14:40 UTC, AlexSCorey commented on frontend/awx/views/schedules/wizard/ScheduleReviewStep.tsx
> +  const timeoutDetail = getValueBasedOnJobType(node_type, '', timeoutString);
```suggestion
  const resourceTypeDetail = useGetNodeTypeDetail(resource_type);
  const timeoutDetail = getValueBasedOnJobType(resource_type, '', timeoutString);
```

2024-04-19 14:40 UTC, AlexSCorey commented on frontend/awx/views/schedules/wizard/ScheduleReviewStep.tsx
> +          <PageDetail label={t('Alias')}>{node_alias}</PageDetail>
```suggestion
```

2024-04-19 19:33 UTC, merged