PageFormCheckbox fix react warnings about unknown html properties
ansible/ansible-ui pull request #2102
Opened 2024-04-18 14:43 UTC by jamestalton

2024-04-18 18:47 UTC, AlexSCorey requested changes

2024-04-18 18:47 UTC, AlexSCorey commented on framework/PageForm/Inputs/PageFormCheckbox.tsx
> +  props.label;
```suggestion

```

2024-04-20 11:43 UTC, vishsanghishetty approved these changes

2024-04-23 13:50 UTC, AlexSCorey approved these changes
Looks good to me.

2024-04-23 13:50 UTC, merged