Update label Help component to handle left margin for spacing
ansible/ansible-ui pull request #2103
Opened 2024-04-18 14:44 UTC by jamestalton

2024-04-18 18:44 UTC, AlexSCorey requested changes
Just removed disabled code.

2024-04-18 18:44 UTC, AlexSCorey commented on framework/components/Help.tsx
>          style={{ padding: 0, marginLeft: marginLeft || '8px', verticalAlign: 'middle' }}
can we remove this?

2024-04-19 19:47 UTC, nixocio approved these changes

2024-04-23 13:49 UTC, AlexSCorey approved these changes
Looks good.

2024-04-23 13:49 UTC, merged