Add boolean to credential details page
ansible/ansible-ui pull request #2123
Opened 2024-04-20 20:39 UTC by nixocio

Add boolen to credential details page

2024-04-21 18:07 UTC, RedOrNot requested changes

2024-04-21 18:07 UTC, RedOrNot commented on cypress/e2e/awx/resources/credentials.cy.ts
> +      cy.get('[data-cy="host"]').clear().type('https://host.com');
can't all the navigation to the right place be in a function?
I see the same lines over and over again , lines 217-221 at least are repeating with different args at cy.selectDropdownOptionByResourceName function 
for example: 
lines 45-49, lines 80-84, lines 111-115
 
and so on

also - from a quick look, you can create 2 function that will cover even more code that repeat itself in this file

2024-04-21 18:48 UTC, RedOrNot commented on cypress/e2e/awx/resources/credentials.cy.ts
> +      cy.get('[data-cy="host"]').clear().type('https://host.com');
will simplify late

2024-04-21 18:48 UTC, RedOrNot approved these changes
LGTM

2024-04-23 20:09 UTC, daphnemaeve approved these changes

2024-04-24 12:40 UTC, merged