eda credential tests
ansible/ansible-ui pull request #2239
Opened 2024-05-04 01:31 UTC by appuk

https://issues.redhat.com/browse/AAP-21822
This PR has:

- [ ] changes to cypress commands for new credential endpoints
- [ ] unskip credential tests
- [ ] new cypress commands for credential types
- [ ] write tests for credentials and credential types for 2.5 scoped

Remaining work that is not reasy for testing yet:

- [ ] bulk delete for credential types
- [ ] auto generate injector button
- [ ] resource usinf a custom credential type

2024-05-06 13:12 UTC, akus062381 requested changes
When running tests on credential-type-crud spec, I see the following test failing:
![image](https://github.com/ansible/ansible-ui/assets/63685497/e7703c7d-36c9-4159-a647-6b72d651810d)
![image](https://github.com/ansible/ansible-ui/assets/63685497/1d428124-280e-470b-911d-4cba01ddbb9e)

2024-05-06 13:24 UTC, akus062381 commented on cypress/e2e/eda/Credentials/credentials-crud.cy.ts
>      cy.edaLogin();
This spec file is looking good!

2024-05-06 13:25 UTC, akus062381 commented on cypress/e2e/eda/Credentials/credentials-list.cy.ts
>      cy.verifyPageTitle('Credentials');
This spec file is looking good!

2024-05-07 16:22 UTC, appuk commented
moved the one failing test to component test as it's not really needed in E2E,
can i get an approval @akus062381 and @vishsanghishetty ??

2024-05-07 16:39 UTC, vishsanghishetty commented
> moved the one failing test to component test as it's not really needed in E2E, can i get an approval @akus062381 and @vishsanghishetty ??

@appuk is that test part of this PR?

2024-05-07 17:04 UTC, appuk commented
> > moved the one failing test to component test as it's not really needed in E2E, can i get an approval @akus062381 and @vishsanghishetty ??
> 
> @appuk is that test part of this PR?

no Laura will be opening another one

2024-05-07 17:04 UTC, vishsanghishetty approved these changes

2024-05-07 17:26 UTC, merged