tests for eda roles
ansible/ansible-ui pull request #2261
Opened 2024-05-08 04:22 UTC by appuk

https://issues.redhat.com/browse/AAP-21630

- [ ] unskip other role tests
- [ ] add tests for custom roles

2024-05-08 04:24 UTC, appuk commented
@akus062381 @vishsanghishetty @vidyanambiar I didn't create custom command for creating/ deleting the custom roles as it is only going to be used in 3 tests. let me know if you still want me to write a custom command for it

2024-05-08 05:01 UTC, appuk commented
@vidyanambiar not sure why lint is failing, can you help me here? Thanks!!

2024-05-08 14:15 UTC, vidyanambiar commented
@appuk Thanks for adding these tests!

The linter error is caused by references to old role interfaces `EdaRole` and `RoleDetail` in the cypress commands/tests. If you replace these references with the interface `EdaRbacRole`, the errors should go away.

2024-05-08 14:56 UTC, akus062381 requested changes

2024-05-08 14:56 UTC, akus062381 commented on cypress/e2e/eda/Roles/custom-roles-crud.cy.ts
> +  it('can delete a custom role', () => {
Hi Apurva! I ran the tests on this spec, and saw the following error with this test:
![image](https://github.com/ansible/ansible-ui/assets/63685497/3f366809-09fe-4da8-abca-15e88cf6204e)

2024-05-08 14:56 UTC, akus062381 commented on cypress/e2e/eda/Roles/eda-role-details.cy.ts
> -// describe('Eda Role Details', () => {
This spec file looks good!

2024-05-08 14:56 UTC, akus062381 commented on cypress/e2e/eda/Roles/eda-roles-list.cy.ts
>  //Tests a user's ability to perform certain actions on the Roles list in the EDA UI.
this spec file looks good!

2024-05-09 13:00 UTC, vishsanghishetty approved these changes
nice work!

2024-05-13 20:12 UTC, akus062381 approved these changes
Looking good! good work

2024-05-13 21:03 UTC, merged