[WIP][AAP-23818] Credentials plugins wizard test button
ansible/ansible-ui pull request #2327
Opened 2024-05-16 02:43 UTC by skochay330

Jira issue: https://issues.redhat.com/browse/AAP-23818

2024-05-21 22:57 UTC, kialam requested changes
Looks good so far. I would move the toast alert into the credentials plugin modal rather than passing it down and remove the unnecessary `else` statement.

2024-05-21 22:57 UTC, kialam commented on frontend/awx/access/credentials/CredentialForm.tsx
> +  const alertToaster = usePageAlertToaster();
I would move this directly into `CredentialPluginsModal` and avoid passing it in to the `useCredentialPluginsModal ` as a hook.

2024-05-21 22:57 UTC, kialam commented on frontend/awx/access/credentials/CredentialForm.tsx
> +  const openCredentialPluginsModal = useCredentialPluginsModal(alertToaster);
```suggestion
  const openCredentialPluginsModal = useCredentialPluginsModal();
```

2024-05-21 22:57 UTC, kialam commented on frontend/awx/access/credentials/CredentialPlugins/CredentialPlugins.tsx
> +    } else
This `else` is unnecessary.

2024-05-21 22:57 UTC, kialam commented on frontend/awx/access/credentials/CredentialPlugins/hooks/useCredentialPluginsDialog.tsx
> +} from '../../../../../../framework';
```suggestion
import {
  IPageAlertToaster,
  PageFormSubmitHandler,
  usePageDialogs,
  usePageAlertToaster
} from '../../../../../../framework';
```

2024-05-21 22:57 UTC, kialam commented on frontend/awx/access/credentials/CredentialPlugins/hooks/useCredentialPluginsDialog.tsx
> +) {
```suggestion
function CredentialPluginsModal(
  props: CredentialPluginsModalProps
) {
```

2024-05-21 22:57 UTC, kialam commented on frontend/awx/access/credentials/CredentialPlugins/hooks/useCredentialPluginsDialog.tsx
>    const { t } = useTranslation();
```suggestion
  const { t } = useTranslation();
  const alertToaster = usePageAlertToaster();
```

2024-05-21 22:57 UTC, kialam commented on frontend/awx/access/credentials/CredentialPlugins/hooks/useCredentialPluginsDialog.tsx
> +          props.alertToaster.addAlert(alert);
```suggestion
          alertToaster.addAlert(alert);
```

2024-05-21 22:57 UTC, kialam commented on frontend/awx/access/credentials/CredentialPlugins/hooks/useCredentialPluginsDialog.tsx
> +          props.alertToaster.addAlert({
```suggestion
          alertToaster.addAlert({
```

2024-05-21 22:57 UTC, kialam commented on frontend/awx/access/credentials/CredentialPlugins/hooks/useCredentialPluginsDialog.tsx
> +export function useCredentialPluginsModal(alertToaster: IPageAlertToaster) {
```suggestion
export function useCredentialPluginsModal() {
```

2024-05-21 22:57 UTC, kialam commented on frontend/awx/access/credentials/CredentialPlugins/hooks/useCredentialPluginsDialog.tsx
> +        <CredentialPluginsModal {...props} onClose={popDialog} alertToaster={alertToaster} />
```suggestion
        <CredentialPluginsModal {...props} onClose={popDialog} />
```

2024-05-21 22:57 UTC, kialam commented on frontend/awx/access/credentials/CredentialPlugins/hooks/useCredentialPluginsDialog.tsx
> +  }, [props, pushDialog, popDialog, alertToaster]);
```suggestion
  }, [props, pushDialog, popDialog]);
```

2024-05-22 14:20 UTC, skochay330 commented on frontend/awx/access/credentials/CredentialPlugins/CredentialPlugins.tsx
> +    } else
Leftover from debugging, good catch!

2024-05-22 16:40 UTC, kialam approved these changes
Should be good to go once the alert toaster is moved into their respective useCredentialPluginsModal and useCredentialTestModal hooks. ⭐

2024-05-23 15:04 UTC, merged