Update AWX roles lists
ansible/ansible-ui pull request #2330
Opened 2024-05-16 18:10 UTC by keithjgrant

Use new RBAC resources for Roles and Teams->Roles lists

2024-05-20 11:58 UTC, vidyanambiar requested changes
- Can we have the associated permissions for a role displayed in an expanded row (similar to EDA)?

- There is an error on pagination to page 3

<img width="548" alt="image" src="https://github.com/ansible/ansible-ui/assets/43621546/859b7fbe-566d-41a8-ba60-0e7eaf96a84f">

2024-05-20 11:58 UTC, vidyanambiar commented on frontend/awx/access/teams/TeamPage/TeamRoles.tsx
> +    <ResourceAccess
Just a heads up - this particular change is related to a work item that @ZitaNemeckova will be addressing [AAP-20560](https://issues.redhat.com/browse/AAP-20560)

2024-05-20 23:24 UTC, keithjgrant commented
> * There is an error on pagination to page 3

Looks like this was caused by the System Auditor role, which has no `content_type` field. I added a catch to cast that to "null" for the sake of the URL. Do you know if this just happens to be bad data in our environment?

2024-05-21 14:24 UTC, vidyanambiar commented
@keithjgrant The System Auditor role is unique in that it has a null content-type because it is applicable system-wide. This is expected.

2024-05-21 16:31 UTC, vidyanambiar approved these changes
Looks great! 🎉 

It would be good to get some component tests added.

2024-05-21 17:38 UTC, merged