[AAP-24645] Instance Details Switch
ansible/ansible-ui pull request #2420
Opened 2024-05-31 18:18 UTC by prat98

Moved instance switch to instance details section so topology view side bar has access to it. Customers can enable and disable an instance from the instances list, instance detail page and topology sidebar now (Just added).
Related JIRA: AAP-24645

2024-06-03 19:17 UTC, AlexSCorey requested changes
Consider using the PageActionSwitch in the details file instead of creating a new Switch file.  Also, lets make the text `Unavailable` red like it is in the list view. ![Screenshot 2024-06-03 at 3 13 48 PM](https://github.com/ansible/ansible-ui/assets/39280967/702573a7-ef6c-4352-b9c9-b599434a53c3)

2024-06-03 19:45 UTC, prat98 commented
Made the requested changes

2024-06-04 13:24 UTC, AlexSCorey reviewed
Looks good to me.

2024-06-04 13:24 UTC, AlexSCorey approved these changes

2024-06-04 15:24 UTC, merged