Assorted Missing Features
ansible/ansible-ui pull request #2438
Opened 2024-06-04 14:48 UTC by AlexSCorey

This addresses AAP-24754, AAP-24954, AAP-24867.  

1) It adds the execution environment look up to the inventory source form, and removes it from the sub form.
It
2) Makes instance group detail view edit button primary
3) Makes detail view DataEditor full width by default.

It also goes through to ensure the Edit buttons in the details views have a primary variant.

2024-06-06 18:14 UTC, prat98 reviewed
I see the ExecutionEnvironment lookup added but it doesn't seem to be adding the EE to the inventory source. Might need the API request being sent

2024-06-06 19:14 UTC, prat98 approved these changes
LGTM! 🚀

2024-06-11 16:06 UTC, marshmalien requested changes
Pulled down but i'm still seeing https://issues.redhat.com/browse/AAP-24954 

![Screenshot 2024-06-11 at 11 59 54 AM](https://github.com/ansible/ansible-ui/assets/15881645/5e889471-e06d-49e7-bf5a-d35df9e7c97f)

2024-06-11 19:04 UTC, marshmalien approved these changes

2024-06-11 19:05 UTC, merged