Update E2E server workflow
ansible/ansible-ui pull request #2576
Opened 2024-06-24 19:06 UTC by kialam

This PR updates our E2E servers upon successful login.

2024-06-24 19:24 UTC, himdel approved these changes

2024-06-24 20:30 UTC, lgalis approved these changes

2024-06-25 14:08 UTC, jamestalton requested changes

2024-06-27 15:00 UTC, jamestalton commented
I'd like to avoiding adding those extra github workflows.
It is easy enough to add them, but makes more to maintain.
What about just performing a curl command on the server to login to verify the server is up and running?

2024-06-28 12:54 UTC, jamestalton approved these changes

2024-06-28 16:06 UTC, kialam commented on .github/workflows/awx-smoke-tests.yml
> +name: AWX Smoke Tests
Spoke with @jamestalton about this and it looks like running a single log in test against a non-matrix would affect our Cypress dashboard results. Instead, we will implement a simple curl login as our test.

2024-06-28 16:08 UTC, merged