[UXD][AAP-25027] AWX - updates to Organizations section breadcrumbs & headers
ansible/ansible-ui pull request #2731
Opened 2024-07-16 14:21 UTC by tiyiprh

https://issues.redhat.com/browse/AAP-25027

Updates to Organizations section breadcrumbs & headers section breadcrumbs & headers

2024-07-18 15:46 UTC, acruzgon requested changes

2024-07-18 15:46 UTC, acruzgon commented on cypress/e2e/awx/access/organizations.cy.ts
> +    cy.verifyPageTitle(`Edit ${organization.name}`);
```suggestion
    cy.verifyPageTitle(organization.name);
```

2024-07-18 15:46 UTC, acruzgon commented on cypress/e2e/awx/access/organizations.cy.ts
> +    cy.verifyPageTitle(`Edit ${organization.name}`);
```suggestion
    cy.verifyPageTitle(organization.name);
```

2024-07-18 15:46 UTC, acruzgon commented on cypress/e2e/awx/access/organizations.cy.ts
> +    cy.verifyPageTitle(`Edit ${organization.name}`);
```suggestion
    cy.verifyPageTitle(organization.name);
```

2024-07-19 09:38 UTC, MilanPospisil submitted a review, later dismissed
LGTM :+1

Ask please @acruzgon if the requested changes were correctly implemented.

2024-08-12 20:13 UTC, acruzgon submitted a review, later dismissed
lgtm!

2024-08-12 20:20 UTC, acruzgon approved these changes
lgtm!

2024-08-12 20:41 UTC, merged