Adds AWX inventory details view
ansible/ansible-ui pull request #344
Opened 2023-03-28 19:27 UTC by mabashian

Add support for inventory details view in AWX.  Currently missing from the implementation is:

1) The Variables detail which will come in a follow-on PR
2) RBAC around the buttons
3) Support for constructed inventories

I'm going to leave this in a draft PR until constructed inventories merges in awx/devel.  Once that merges, I'll update this PR to support constructed inventories and possibly add RBAC to the buttons.

2023-04-03 16:17 UTC, vidyanambiar approved these changes
Looks good 👍  A couple comments below:

- Not seeing Credentials and Labels in this implementation. Could those be added in a future PR as well?
- The awx UI has help texts for certain fields. This may be a framework level discussion since it applies to various details pages and not only templates.

2023-04-04 14:25 UTC, jamestalton requested changes

2023-04-04 14:25 UTC, jamestalton commented on frontend/awx/interfaces/Inventory.ts
> -export interface Inventory extends Omit<SwaggerInventory, 'id' | 'name' | 'summary_fields'> {
This removes the usage of the interface that is generated from swagger.
Whats the thoughts behind this?

2023-04-04 14:25 UTC, jamestalton commented on frontend/awx/resources/inventories/InventoryPage/InventoryDetails.tsx
> +  useEffect(() => {
instead of this effect a call to useGet should work better here

2023-04-04 21:39 UTC, mabashian commented on frontend/awx/interfaces/Inventory.ts
> +  verbosity?: never;
@jamestalton I wrote a hook that converts the value that the api gives us for verbosity into the string that we want to show in the UI: frontend/awx/common/useVerbosityString.tsx.  In the case of inventories, verbosity is only available for constructed inventories and I couldn't figure out how to call that hook without the linter getting mad that verbosity may not be defined.  To get around that I went down the `never` route but I'm not sure how accepted this route is.  You can reproduce the scenario I'm talking about by removing this line and then going and looking at my call to useVerbosityString in InventoryDetails.

2023-04-05 19:05 UTC, jamestalton approved these changes
lgtm

2023-04-06 17:11 UTC, merged