Create/ Edit project
ansible/ansible-ui pull request #571
Opened 2023-05-18 21:47 UTC by vidyanambiar

- Form for creating and editing AWX projects
- Minor update to the framework to allow numeric fields to have a minimum value
- Hook `useGetCredentialTypeIDs` to get credential type IDs (required for looking up credentials of a specific type)
- Updates to `PageFormCredentialSelect.tsx` to look up credentials of a specific type, and to support single selection 
- E2E tests

WIP: component tests

<img width="1143" alt="image" src="https://github.com/ansible/ansible-ui/assets/43621546/237bccf2-eba6-4fca-b5dd-33c21ed1e790">

2023-05-22 13:33 UTC, AlexSCorey commented
On edit in AWX, when the user changes the project type, the sub form resets with empty values.  If the user then returns the project type to the original type, the original values render.  We should probably duplicate this behavior

2023-05-22 13:57 UTC, AlexSCorey commented
Found a bug when editing a project from something with scm credential to red hat insights with a redhat insights credential

![credentialBug](https://github.com/ansible/ansible-ui/assets/39280967/a42b28f9-3789-4dfe-808d-0c8fc81fd520)

2023-05-22 14:22 UTC, AlexSCorey commented
Projects of type `git` should not have the `cache timeout` option.  This is when editing a project
![Screen Shot 2023-05-22 at 10 21 16 AM](https://github.com/ansible/ansible-ui/assets/39280967/b4dc98f4-8b4f-45ca-aa1d-da4c1ef5759b)

2023-05-22 15:57 UTC, AlexSCorey requested changes
This is a great start.  Found some bugs and some commented out code to be removed.  Let me know when its ready for another look.

2023-05-23 13:38 UTC, vidyanambiar commented on frontend/awx/resources/projects/ProjectSubForms/ManualSubForm.tsx
> +  const product: string = process.env.PRODUCT ?? t('Ansible');
We have several instances of this in the code. I agree that having a hook would be useful here. It's better addressed separately from this PR I think. I will get an issue opened for it.

2023-05-23 13:42 UTC, vidyanambiar commented
@AlexSCorey Thanks for the review! I think I've got all your comments addressed. The bugs you saw seemed related to an earlier comment about resetting the SCM form fields correctly when the source control type is changed.
Could you re-review please?

2023-05-23 14:58 UTC, AlexSCorey approved these changes
I've pulled this down and all of my concerns have been addressed.  Well done!

2023-06-05 15:28 UTC, vidyanambiar commented
This was merged in https://github.com/ansible/ansible-ui/pull/581/commits

2023-06-05 15:28 UTC, closed without merging