[EDA] Fix broken user details and user tokens views for non-admins and non-auditors
ansible/ansible-ui pull request #578
Opened 2023-05-23 03:02 UTC by marshmalien

https://issues.redhat.com/browse/AAP-11573

* Fix bug where users without admin or auditor roles could not create or view their tokens
* Fix bug where users without admin or auditor roles could not view their details via the masthead dropdown
* Add `/users/me` and `/users/me/tokens` EDA routes

**When user does not have Admin role:**
* Hide user details edit and delete actions

**When user does not have Admin or Auditor roles:** 
* Hide Access sidebar group
* Hide users breadcrumb route
* GET user details from `api/eda/v1/users/me` instead of `api/eda/v1/users/:id`

**When user is viewing self** 
* Show Controller Tokens tab 

![permissions](https://github.com/ansible/ansible-ui/assets/15881645/4d7c57a1-6d47-41d3-9c48-5f9ebceaf091)

**Note**
Ideally I would've moved user, roles, and permissions into a context provider that wrapped the EventDriven page. Adding that new functionality would've remove duplicate calls to `EdaUserInfo()`, but it was not necessary for this bug fix and it bloated the PR.

2023-05-23 18:56 UTC, vishsanghishetty approved these changes
lgtm 🚀

2023-06-09 14:58 UTC, lgalis requested changes
The User

2023-06-09 14:58 UTC, lgalis commented on frontend/eda/EventDrivenSidebar.tsx
> +  const canViewAccess =
The canViewAccess should also return true is the user is a superuser: activeUser?.is_superuser. The superuser does not have any roles returned.

2023-06-13 19:19 UTC, lgalis approved these changes
LGTM

2023-06-27 22:34 UTC, lgalis requested changes
Please rebase as well so the e2e tests will pass and we can merge this PR.
Thank you!

2023-06-27 22:34 UTC, lgalis commented on frontend/eda/UserAccess/Users/EdaUserDetails.tsx
> +  const canEditUser = activeUser?.roles.some((role) => role.name === 'Admin');
There should be a check for activeUser?.is_superuser here

2023-06-27 22:34 UTC, lgalis commented on frontend/eda/UserAccess/Users/EdaUserDetails.tsx
> +  const canViewUsers = activeUser?.roles.some(
...and here

2023-07-07 14:51 UTC, merged