Add initial remote form
ansible/ansible-ui pull request #720
Opened 2023-07-21 19:57 UTC by nixocio

Add initial remote form, modify related files. This one will be expanded to deal with edge cases, and yaml/json upload field.

See: https://issues.redhat.com/browse/AAH-2493

![image](https://github.com/ansible/ansible-ui/assets/9053044/bc2a1dda-40fe-4938-b6a8-a56b52e80682)

2023-07-27 14:23 UTC, AlexSCorey requested changes
This looks great.  I have just proposed a few changes.

2023-07-27 18:44 UTC, nixocio commented on frontend/hub/remotes/RemoteForm.tsx
> +          <PageFormSection singleColumn>
@AlexSCorey, that is a good suggestion, let me take a look.

2023-07-28 13:31 UTC, AlexSCorey approved these changes
Looks good to me.

2023-07-31 20:31 UTC, vidyanambiar reviewed
Nice work 🎉  

Curious, why does the URL require a slash at the end? I was able to save a URL without slash in ansible-hub-ui.
- If the URL does not end in `/` an error is displayed, but this error does not go away when the slash is added at the end of the URL
<img width="630" alt="image" src="https://github.com/ansible/ansible-ui/assets/43621546/fdae81b8-1673-4bb8-834c-40e28892897e">

- Can we add checks to validate URL? Currently it is possible to just save `/` as the value of URL.

2023-08-01 13:13 UTC, nixocio commented on frontend/hub/remotes/RemoteForm.tsx
> +function CeriticatesAdvancedRemoteInputs() {
@vidyanambiar the ansible-hub-ui frontend client is appending a `/` to the URL. I will add the same logic. The trailing slash is required by design on the backend.

2023-08-01 19:55 UTC, vidyanambiar approved these changes
As discussed offline URL validation will be added in follow on PRs. This looks good to me. 👍

2023-08-01 19:59 UTC, merged