Job output follow mode & scroll buttons
ansible/ansible-ui pull request #727
Opened 2023-07-25 17:45 UTC by keithjgrant

Adds follow mode & pagination buttons to the job output page

* Clicking Unfollow exits follow mode
* Clicking page up or scroll to top buttons exits follow mode
* Scrolling manually does *not* exit follow mode -- I decided I cannot rely on `onScroll` events to exit follow mode, because follow mode itself fires off so many of them and I could not reliably distinguish between those and user-driven scroll events
* Clicking the scroll to bottom button enables follow mode. This enables the UI to scroll to bottom repeatedly so it stays at the bottom while the last events load and render.
* If the job is not running and follow mode is enabled, it will wait until the output has been locked to the bottom consistently for 600ms (checking every 200ms) -- allowing for the final events to render & resize properly -- then it will automatically disable follow mode.

2023-07-25 19:02 UTC, jamestalton approved these changes
lgtm

2023-08-01 18:33 UTC, akus062381 requested changes
@keithjgrant I am testing this now. Upon completion of a job, scrolling up within the output window doesn't work. I can show you if you would like.

2023-08-09 20:04 UTC, vidyanambiar approved these changes

2023-08-17 18:57 UTC, akus062381 approved these changes

2023-08-17 22:16 UTC, merged