Adds workflow job template form, and details
ansible/ansible-ui pull request #799
Opened 2023-08-21 20:54 UTC by AlexSCorey

Adds Workflow Job Template Form and Workflow Job Template Detail View

2023-08-30 19:45 UTC, jamestalton requested changes

2023-08-30 19:45 UTC, jamestalton commented on cypress/e2e/awx/resources/workflowJobTemplates.cy.ts
> +    cy.contains('.pf-c-form__label-text', /^Job tags$/)
There are cy custom commands for handling this.
using a bunch of cy command like this is going to make upgrading to PF5 hard.

2023-08-30 19:45 UTC, jamestalton commented on frontend/awx/resources/templates/WorkflowJobTemplateForm.tsx
> +    } catch (err) {
should not need this catch. the form will catch it and display the error.

2023-08-30 19:45 UTC, jamestalton commented on frontend/awx/resources/templates/WorkflowJobTemplateForm.tsx
> +    } catch (err) {
same. i do not think we should have to have this catch as the form handles it

2023-09-01 16:09 UTC, marshmalien commented on frontend/awx/resources/templates/WorkflowJobTemplateInputs.tsx
> +      />
Could we move these two checkboxes into a separate form section? When the form is in 3 columns, the checkboxes get split up. 
<img width="1169" alt="Screenshot 2023-09-01 at 12 07 50 PM" src="https://github.com/ansible/ansible-ui/assets/15881645/a9401bd3-3f28-4a1e-8cd1-55f76de74c2d">

2023-09-01 16:24 UTC, marshmalien requested changes

2023-09-01 16:24 UTC, marshmalien commented on frontend/awx/resources/templates/WorkflowJobTemplateForm.tsx
> +    });
We don't need to send `summary_fields` on workflow template creation. I think the API is expecting a payload that looks something like this: 
```
interface WFCreation {
  allow_simultaneous: boolean;
  ask_inventory_on_launch: boolean;
  ask_labels_on_launch: boolean;
  ask_limit_on_launch: boolean;
  ask_scm_branch_on_launch: boolean;
  ask_skip_tags_on_launch: boolean;
  ask_tags_on_launch: boolean;
  ask_variables_on_launch: boolean;
  description: string;
  extra_vars: string;
  inventory: number;
  job_tags: string;
  limit: string;
  name: string;
  organization: number;
  scm_branch: string;
  skip_tags: string;
  survey_enabled: boolean;
  webhook_credential: number;
  webhook_service: 'github' | 'gitlab' | '';
}
```

2023-09-06 15:19 UTC, marshmalien commented on frontend/awx/resources/templates/WorkflowJobTemplateForm.tsx
> +    postRequest(`/api/v2/worflow_job_templates/${template.id.toString()}/labels/`, {
Workflow labels URL spelling 
`/api/v2/workflow_job_templates/...`

2023-09-15 14:47 UTC, marshmalien approved these changes
Looks great! Nice work on the forms 🔥

2023-09-20 13:05 UTC, vishsanghishetty approved these changes

2023-09-20 17:05 UTC, jamestalton approved these changes
lgtm

2023-09-20 17:05 UTC, jamestalton commented on cypress/support/component.tsx
> +Cypress.Commands.add('mount', (component, route, fixture) => {
fixture is too generic here. it's the fixture for the active user correct?
maybe activeUserFixture?

2023-09-20 17:51 UTC, merged