[AAP-11862] [AAP-12169][AAP-12496] Allow credentials deselect
ansible/ansible-ui pull request #862
Opened 2023-09-06 12:58 UTC by lgalis

Allow credentials deselect on the Project and Decision Environments create/edit forms:

![Screenshot from 2023-09-18 16-46-10](https://github.com/ansible/ansible-ui/assets/12769982/9a6ad48f-2ec4-43c9-9d03-8b3454dfc31b)
![Screenshot from 2023-09-18 16-46-00](https://github.com/ansible/ansible-ui/assets/12769982/ce0c871f-30fa-4682-a178-0025efe06a1f)

2023-09-18 21:08 UTC, vishsanghishetty approved these changes
lgtm 🚀

2023-09-19 12:59 UTC, jamestalton requested changes

2023-09-19 18:46 UTC, lgalis commented on framework/PageForm/Inputs/PageFormSelect.tsx
> +    isClearable,
updated

2023-09-19 19:29 UTC, jamestalton approved these changes
lgtm

2023-09-19 20:10 UTC, merged