Move error alert to the top of PageForm component
ansible/ansible-ui pull request #867
Opened 2023-09-07 17:19 UTC by nixocio

Move error alert to the top of PageForm component

Also, update padding on the Alert component to align with the remaining page structure.

<img width="1433" alt="image" src="https://github.com/ansible/ansible-ui/assets/9053044/5aad37c4-9eff-4dcf-8820-fad6a14fd413">

2023-09-07 18:52 UTC, AlexSCorey reviewed
If we are going to move this error I think it should be sticky and always visible, even when the user scrolls down to the bottom on a long, single column form.  I would get very confused if I scrolled to the bottom of a form to submit it, but wasn't alerted to the error because it was hidden at the top.

2023-09-08 18:58 UTC, nixocio commented
I added this change @AlexSCorey 

<img width="1425" alt="image" src="https://github.com/ansible/ansible-ui/assets/9053044/8ab040a9-62d6-4cbb-99e9-c51f8524a030">

2023-09-11 16:37 UTC, jamestalton requested changes

2023-09-11 16:37 UTC, jamestalton commented on framework/PageForm/PageForm.tsx
> +              position: 'sticky',
i'd like to avoid sticky.
I think the alert should be outside the scrollable area of the form

2023-10-04 17:25 UTC, closed without merging