Add docs for string casing, adds href to side nav, updates translation logic
ansible/ansible-ui pull request #929
Opened 2023-09-20 17:54 UTC by AlexSCorey

This PR has 2 commits.  The first 1 addresses AAP-10882 and AAP-10495.  I addressed AAP-10882 by making some updates to the string casing in AWX, and by adding documentation to CONTRIBUTING.md file to help those that may have questions about it in the future.  

The second commit removes the useFrameworkTranslations hook, and the file it was defined it.  Instead, we wrap the app in a I18nProvider that gives the whole app access to the translated strings.

2023-09-20 18:10 UTC, vishsanghishetty approved these changes

2023-09-20 19:57 UTC, jamestalton requested changes

2023-09-20 19:57 UTC, jamestalton commented on CONTRIBUTING.md
> +### Text
This should prob be in https://github.com/ansible/ansible-ui/blob/main/docs/CAPITALIZATION.md

2023-09-25 14:26 UTC, jamestalton approved these changes
lgtm

2023-09-26 13:50 UTC, merged